training_pipeline_config:
  pipeline_name: avila_classifier
  artifact_dir: artifact

data_ingestion_config:
  data_download_url: https://archive.ics.uci.edu/ml/machine-learning-databases/00459/avila.zip
  raw_data_dir: raw_data
  zip_download_dir: zip_data
  ingested_data_dir: ingested_dir
  ingested_train_data_dir: train
  ingested_test_data_dir: test

data_validation_config:
  schema_dir: config
  schema_file_name: schema.yaml
  report_file_name: report.json
  report_page_file_name: report.html

data_analysis_config:
  profiling_page_file_name: train_profile.html

data_transformation_config:
  transformed_dir: transformed_data
  transformed_train_dir: train
  transformed_test_dir: test

model_config:
  model_dir: trained_model
  best_model: model.pkl
  score: score.json
  