name: heroku deployment

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker container to heroku
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: jj_alavego@yahoo.com
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: avila_classifier
          dockerfile_directory: ./
          dockerfile_name: Dockerfile
          docker_options: "--no-cache"
          process_type: web
